[package]
name = "s-autoscroller"
version = "0.1.0"
edition = "2024"

[dependencies]
device_query = "4.0.1"
mouse-keyboard-input = "0.9.1"
notify-rust = "4.11.7"
rust-ini = "0.21.3"
softbuffer = "0.4.8"
winit = "0.30.12"

